### ISSUE TITLE
bootstrap failed

### ISSUE THREAD

**Issue by ppstudy-code** [named-data-iot/ndn-iot-package-over-posix#10]
i do according to README until b.click bootstrap，it shows bootstap failed，can you help me？

**Comment by tanim-ics** [comment]
Hello, I am facing the same issue. I followed the same steps..but when I am executing tutorial-app, it is not working. bootstrapping is getting failed. 

On the NFD, I turned on the forwarder trace from the nfd.conf file. I found that tutorial-app is sharing the secret key to the controller. But NFD does not know where to forward it. 

How did you solve the issue? Can you please give me a direction?
