### ISSUE TITLE
compile ERROR on examples/tutorial-app-sub.c for missing policy_start() function

### ISSUE THREAD

**Issue by breakbambino** [named-data-iot/ndn-iot-package-over-posix#12]
~/ndn-iot-package-over-posix/build$ make -j2

CMakeFiles/tutorial-app-sub.dir/examples/tutorial-app-sub.c.o: In function `after_bootstrapping':
tutorial-app-sub.c:(.text+0x221): undefined reference to `policy_start'
collect2: error: ld returned 1 exit status
CMakeFiles/tutorial-app-sub.dir/build.make:95: recipe for target 'examples/tutorial-app-sub' failed
make[2]: *** [examples/tutorial-app-sub] Error 1
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/tutorial-app-sub.dir/all' failed
make[1]: *** [CMakeFiles/tutorial-app-sub.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tianyuan129** [comment]
I updated and partially disabled policy related features. Now tutorial-app and tutorial-app-sub work fine.
