### ISSUE TITLE
CMake build requirement

### ISSUE THREAD

**Issue by Pesa** [named-data-iot/ndn-iot-package-over-posix#4]
I think the current requirement of cmake >= 3.11 is pretty high. The latest Ubuntu LTS has 3.10.2 (https://packages.ubuntu.com/bionic/cmake), which makes it hard to build this package on Ubuntu, since most people only use LTS releases.

I wonder if it's feasible to slightly lower the requirement to >= 3.10 ?

**Comment by yoursunny** [comment]
If you intend to support Raspbian, lower the requirement to [cmake 3.7.2](https://packages.debian.org/stretch/cmake) as it's the version packaged by Debian Stretch and used in current Raspbian release.

**Comment by zjkmxy** [comment]
I think it's possible to lower it to 3.10 because currently we only need the following feature of 3.11:

> add_library() and add_executable() commands can now be called without any sources and will not complain as long as sources are added later via the target_sources() command.

But I'm not sure if I can make it to 3.7. I will have a try.

**Comment by Pesa** [comment]
Thanks. You forgot to update the README, it still says "CMake >= 3.11"
