### ISSUE TITLE
Is NFD supported on ndn-lite?

### ISSUE THREAD

**Issue by vaynetian** [named-data-iot/ndn-iot-package-over-posix#8]

**Comment by yoursunny** [comment]
Yes, an ndn-lite-POSIX app can connect to NFD via unix_face.
Example: https://github.com/named-data-iot/ndn-iot-package-over-posix/blob/64f92b6557052fe6578e257d55accd14dcd31d7f/examples/nfd-basic-consumer.c

**Comment by vaynetian** [comment]
@yoursunny Thanks, but NFD now is based on ndn-cxx. How can NFD be installed without ndn-cxx, and then work with ndn-lite-POSIX?

**Comment by yoursunny** [comment]
> How can NFD be installed without ndn-cxx

This is not possible. ndn-lite-POSIX is not a drop-in replacement of ndn-cxx.

On the other hand, ndn-lite provides a forwarder, so ndn-lite can partially replace NFD.
However, ndn-lite forwarder is not fully complaint and only supports a subset of required forwarding features.
